# image will be published to ghcr.io/<user>/<name>
name: Silverwing
# description will be included in the image's metadata
description: My spin of Wayblue Hyprland. 

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland # Wayblue Hyprland is the base.
image-version: 41 # latest is also supported if you want new updates ASAP

modules:
  - from-file: default-files.yml
  - from-file: virtualization.yml # libvert and virt-manager
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
